// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9IoZp3K67MELZQOZQweGyKWin9q7lUb8',
    appId: '1:1041288545392:web:4242cad821b19f5a25a0b5',
    messagingSenderId: '1041288545392',
    projectId: 'cota-frete-estudo',
    authDomain: 'cota-frete-estudo.firebaseapp.com',
    databaseURL: 'https://cota-frete-estudo-default-rtdb.firebaseio.com',
    storageBucket: 'cota-frete-estudo.appspot.com',
    measurementId: 'G-FR08559ES6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvhlOQjfhFZmEI8JaQshbVbv5fazSB-1A',
    appId: '1:1041288545392:android:7af3fab18c7ed6a325a0b5',
    messagingSenderId: '1041288545392',
    projectId: 'cota-frete-estudo',
    databaseURL: 'https://cota-frete-estudo-default-rtdb.firebaseio.com',
    storageBucket: 'cota-frete-estudo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDR3ZzBMhKBWzIIoJHRe8Qx3xrbyWOKmGQ',
    appId: '1:1041288545392:ios:d6d456cf02d2d7ab25a0b5',
    messagingSenderId: '1041288545392',
    projectId: 'cota-frete-estudo',
    databaseURL: 'https://cota-frete-estudo-default-rtdb.firebaseio.com',
    storageBucket: 'cota-frete-estudo.appspot.com',
    iosClientId: '1041288545392-7vil9hj5ot1o0dh7812i6c6mo8f2cejv.apps.googleusercontent.com',
    iosBundleId: 'br.com.cotafrete.app',
  );
}
